steps:
  - label: ":docker: Build"
    plugins:
      - docker-login#v2.0.1:
          username: bsteffaniak
          password-env: DOCKER_LOGIN_PASSWORD
      - docker-compose#v3.1.0:
          build: app
          config: docker-compose.buildkite.yml
          image-repository: bsteffaniak/nova
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "app"
      BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.buildkite.yml"
      COMPOSE_HTTP_TIMEOUT: 600
    timeout_in_minutes: 10

  - wait

  - label: "Exceptions"
    command: .buildkite/build-scripts/exception-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Syntax"
    command: .buildkite/build-scripts/syntax-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Closures"
    command: .buildkite/build-scripts/closure-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Polymorphism"
    command: .buildkite/build-scripts/polymorphism-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Lambdas"
    command: .buildkite/build-scripts/lambda-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "ToString"
    command: .buildkite/build-scripts/tostring-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Assignments"
    command: .buildkite/build-scripts/assignment-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Regex"
    command: .buildkite/build-scripts/regex-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Static Imports"
    command: .buildkite/build-scripts/static-import-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Inner Classes"
    command: .buildkite/build-scripts/inner-class-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "External Inner Classes"
    command: .buildkite/build-scripts/external-inner-class-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Primitive Overloads"
    command: .buildkite/build-scripts/primitive-overload-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Fancy Output Stream"
    command: .buildkite/build-scripts/fancy-output-stream-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "First Class Functions"
    command: .buildkite/build-scripts/first-class-function-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Library Loading"
    command: .buildkite/build-scripts/library-loading-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Intervals"
    command: .buildkite/build-scripts/interval-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Bounded Intervals"
    command: .buildkite/build-scripts/bounded-interval-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Boundless Intervals"
    command: .buildkite/build-scripts/boundless-interval-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app

  - label: "Casts"
    command: .buildkite/build-scripts/cast-stability.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app
