steps:
  - name: "Syntax Stability"
    command: ./executable
    plugins:
      docker-compose:
        build: app
        config: docker-compose.buildkite.yml
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "app"
      BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.buildkite.yml"
      COMPOSE_HTTP_TIMEOUT: 600
    timeout_in_minutes: 10
    retry:
      automatic:
        limit: 1