steps:
  - name: "Syntax Stability"
    command: ./executable
    plugins:
      - docker#v3.3.0:
          image: "node:12.13.0"
      - docker-compose#v3.1.0:
          build: app
          image-repository: index.docker.io/bsteffaniak/nova
          config: docker-compose.buildkite.yml
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "app"
      BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.buildkite.yml"
      COMPOSE_HTTP_TIMEOUT: 600
    timeout_in_minutes: 10