steps:
  - name: "Syntax Stability"
    command: ./executable
    plugins:
      docker-compose:
        build: app
        config: docker-compose.buildkite.yml
        image-repository: ecr.us-west-2.amazonaws.com/buildkite
    retry:
      automatic:
        limit: 1