steps:
  - label: ":docker: Build"
    plugins:
      - docker-login#v2.0.1:
          username: bsteffaniak
          password-env: DOCKER_LOGIN_PASSWORD
      - docker-compose#v3.1.0:
          build: app
          config: docker-compose.buildkite.yml
          image-repository: bsteffaniak/nova
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "app"
      BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.buildkite.yml"
      COMPOSE_HTTP_TIMEOUT: 600
    timeout_in_minutes: 10

  - wait

  - label: "Test"
    command: executable
    plugins:
      - docker-compose#v3.1.0:
          run: app