steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.1.0:
          build: app
          config: docker-compose.buildkite.yml
          image-repository: 442998785547.dkr.ecr.us-west-2.amazonaws.com/buildkite
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "app"
      BUILDKITE_DOCKER_COMPOSE_FILE: "docker-compose.buildkite.yml"
      COMPOSE_HTTP_TIMEOUT: 600
    timeout_in_minutes: 10

  - wait

  - label: "Test"
    command: test.sh
    plugins:
      - docker-compose#v3.1.0:
          run: app